"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { SitePreview } from "../../components/site-preview";
import { defaultProject, isTemplateId, slugify, templates, type ProjectInput } from "../../lib/project";

const emptyResult = { id: "", slug: "" };
const copy = {
  tr: { studio: "QUICKSITE STUDIO", title: "Siteni detaylarıyla hazırla.", sub: "Bilgileri değiştir; sonuç sağ tarafta anında görünsün.", template: "Şablon", language: "Site ve form dili", color: "Ana renk", business: "İşletme ve marka", businessName: "İşletme adı", industry: "Sektör", eyebrow: "Üst kısa başlık", headline: "Ana başlık", description: "Kısa açıklama", cta: "Ana buton yazısı", hours: "Çalışma saatleri", aboutTitle: "Hakkımızda başlığı", menu: "Menü ürünleri", services: "Hizmetler / teklifler", addItem: "+ Yeni öğe ekle", remove: "Sil", benefits: "Öne çıkan avantajlar", addBenefit: "+ Avantaj ekle", media: "Logo, kapak ve galeri", logo: "Logo görsel bağlantısı", hero: "Kapak görsel bağlantısı", gallery: "Galeri görselleri", contact: "İletişim ve yayın", person: "Yetkili kişi", email: "E-posta", phone: "Telefon", whatsapp: "WhatsApp", address: "Adres", instagram: "Instagram", map: "Google Maps bağlantısı", slug: "İstediğin yayın adresi", note: "AuraDigital’e notun", notePlaceholder: "Özel istek, ödeme bilgisi veya açıklama…", submit: "Taslağı onaya gönder", submitting: "Kaydediliyor…", topSubmit: "Onaya gönder", live: "Canlı önizleme", unsaved: "Kaydedilmemiş taslak", validation: "İşletme adı, yetkili kişi ve e-posta alanlarını doldurun.", received: "TALEP ALINDI", ready: "Siten hazır.", waiting: "Şimdi AuraDigital onayı bekliyor.", waitingText: "Talebin yönetim ekranına düştü. Ödeme ve içerik onaylandıktan sonra kırmızı durum yeşile dönecek ve adresin aktif olacaktır.", view: "Taslağı görüntüle", home: "Ana sayfaya dön", status: "Ödeme ve onay bekliyor" },
  en: { studio: "QUICKSITE STUDIO", title: "Build your site in detail.", sub: "Edit the information and see every change instantly on the right.", template: "Template", language: "Website and form language", color: "Primary color", business: "Business and brand", businessName: "Business name", industry: "Industry", eyebrow: "Small top heading", headline: "Main headline", description: "Short description", cta: "Primary button text", hours: "Working hours", aboutTitle: "About section title", menu: "Menu items", services: "Services / offers", addItem: "+ Add item", remove: "Remove", benefits: "Key benefits", addBenefit: "+ Add benefit", media: "Logo, cover and gallery", logo: "Logo image URL", hero: "Cover image URL", gallery: "Gallery images", contact: "Contact and publishing", person: "Contact person", email: "Email", phone: "Phone", whatsapp: "WhatsApp", address: "Address", instagram: "Instagram", map: "Google Maps URL", slug: "Preferred publishing address", note: "Note for AuraDigital", notePlaceholder: "Special request, payment information or explanation…", submit: "Submit draft for approval", submitting: "Saving…", topSubmit: "Submit request", live: "Live preview", unsaved: "Unsaved draft", validation: "Complete the business name, contact person and email fields.", received: "REQUEST RECEIVED", ready: "Your site is ready.", waiting: "It is waiting for AuraDigital approval.", waitingText: "Your request is now in the owner dashboard. After payment and content approval, the red status turns green and your address becomes active.", view: "View draft", home: "Back to home", status: "Waiting for payment and approval" },
  ar: { studio: "QUICKSITE STUDIO", title: "أنشئ موقعك بكل التفاصيل.", sub: "عدّل المعلومات وشاهد النتيجة فوراً في المعاينة.", template: "القالب", language: "لغة الموقع والنموذج", color: "اللون الرئيسي", business: "النشاط والعلامة", businessName: "اسم النشاط", industry: "المجال", eyebrow: "العنوان العلوي القصير", headline: "العنوان الرئيسي", description: "وصف مختصر", cta: "نص الزر الرئيسي", hours: "ساعات العمل", aboutTitle: "عنوان من نحن", menu: "عناصر القائمة", services: "الخدمات والعروض", addItem: "+ إضافة عنصر", remove: "حذف", benefits: "المزايا الرئيسية", addBenefit: "+ إضافة ميزة", media: "الشعار والغلاف والمعرض", logo: "رابط صورة الشعار", hero: "رابط صورة الغلاف", gallery: "صور المعرض", contact: "التواصل والنشر", person: "الشخص المسؤول", email: "البريد الإلكتروني", phone: "الهاتف", whatsapp: "واتساب", address: "العنوان", instagram: "إنستغرام", map: "رابط خرائط Google", slug: "عنوان النشر المطلوب", note: "ملاحظة إلى AuraDigital", notePlaceholder: "طلب خاص أو معلومات الدفع أو توضيح…", submit: "إرسال المسودة للموافقة", submitting: "جارٍ الحفظ…", topSubmit: "إرسال الطلب", live: "معاينة مباشرة", unsaved: "مسودة غير محفوظة", validation: "أكمل اسم النشاط والشخص المسؤول والبريد الإلكتروني.", received: "تم استلام الطلب", ready: "موقعك جاهز.", waiting: "بانتظار موافقة AuraDigital.", waitingText: "ظهر طلبك الآن في لوحة المالك. بعد تأكيد الدفع والمحتوى يتحول اللون الأحمر إلى أخضر ويتم تفعيل الرابط.", view: "عرض المسودة", home: "العودة للرئيسية", status: "بانتظار الدفع والموافقة" },
};

export default function BuilderClient() {
  const params = useSearchParams();
  const requestedTemplate = params.get("template") ?? "";
  const [project, setProject] = useState<ProjectInput>(() => ({ ...defaultProject, offers: defaultProject.offers.map((item) => ({ ...item })), benefits: [...defaultProject.benefits], galleryUrls: [...defaultProject.galleryUrls], templateId: isTemplateId(requestedTemplate) ? requestedTemplate : defaultProject.templateId }));
  const [view, setView] = useState<"desktop" | "mobile">("desktop");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState(emptyResult);
  const text = copy[project.language] ?? copy.tr;
  const rtl = project.language === "ar";

  useEffect(() => { window.localStorage.setItem("auradigital-builder-draft", JSON.stringify(project)); }, [project]);
  const update = <K extends keyof ProjectInput>(key: K, value: ProjectInput[K]) => setProject((current) => ({ ...current, [key]: value }));
  const updateOffer = (index: number, key: "name" | "description" | "price", value: string) => setProject((current) => ({ ...current, offers: current.offers.map((offer, offerIndex) => offerIndex === index ? { ...offer, [key]: value } : offer) }));
  const updateList = (key: "benefits" | "galleryUrls", index: number, value: string) => setProject((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? value : item) }));
  const selectedTemplate = useMemo(() => templates.find((item) => item.id === project.templateId) ?? templates[0], [project.templateId]);
  const menuSite = project.templateId === "nova-menu" || project.templateId === "espresso";

  function addOffer() { if (project.offers.length < 12) update("offers", [...project.offers, { name: "", description: "", price: "" }]); }
  function removeOffer(index: number) { if (project.offers.length > 1) update("offers", project.offers.filter((_, itemIndex) => itemIndex !== index)); }
  function addBenefit() { if (project.benefits.length < 6) update("benefits", [...project.benefits, ""]); }
  function removeBenefit(index: number) { update("benefits", project.benefits.filter((_, itemIndex) => itemIndex !== index)); }

  async function submit() {
    setError("");
    if (!project.businessName.trim() || !project.email.trim() || !project.contactName.trim()) { setError(text.validation); return; }
    setSaving(true);
    try {
      const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...project, slug: slugify(project.slug || project.businessName) }) });
      const payload = await response.json() as { project?: { id: string; slug: string }; error?: string };
      if (!response.ok || !payload.project) throw new Error(payload.error || "Request could not be submitted.");
      setResult(payload.project);
      window.localStorage.removeItem("auradigital-builder-draft");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Request could not be submitted."); }
    finally { setSaving(false); }
  }

  if (result.id) return <main className="submitted-page" dir={rtl ? "rtl" : "ltr"}><div className="submitted-card"><div className="submitted-icon"><span className="status-dot pending" /></div><span className="kicker">{text.received}</span><h1>{text.ready}<br />{text.waiting}</h1><p>{text.waitingText}</p><div className="submission-status"><span className="status-dot pending" /><div><b>{text.status}</b><small>auradigital.ink/quicksite/{result.slug}</small></div></div><div className="submitted-actions"><Link className="button button-dark" href={`/quicksite/preview/${result.id}`}>{text.view}</Link><Link className="text-link dark-text" href="/quicksite">{text.home}</Link></div></div></main>;

  return (
    <main className="studio-page">
      <header className="studio-header"><Link className="brand" href="/quicksite"><span className="brand-mark">A<span>•</span></span><span>auradigital</span></Link><div className="studio-progress"><span className="done">1</span><i /><span className="done">2</span><i /><span>3</span><b>{text.live}</b></div><button className="button button-small" onClick={submit} disabled={saving}>{saving ? text.submitting : text.topSubmit}</button></header>
      <div className="studio-layout">
        <aside className="editor-panel" dir={rtl ? "rtl" : "ltr"}>
          <div className="editor-heading"><span className="kicker">{text.studio}</span><h1>{text.title}</h1><p>{text.sub}</p></div>
          <div className="editor-section"><label>{text.template}</label><div className="template-select-grid">{templates.map((item) => <button type="button" key={item.id} className={item.id === project.templateId ? "active" : ""} onClick={() => update("templateId", item.id)}><i className={`template-chip chip-${item.id}`} /> <span>{item.name}<small>{item.category}</small></span></button>)}</div></div>
          <div className="editor-section"><div className="field-row"><label>{text.language}<select value={project.language} onChange={(event) => update("language", event.target.value as ProjectInput["language"])}><option value="tr">Türkçe</option><option value="en">English</option><option value="ar">العربية</option></select></label><label>{text.color}<span className="color-field"><input type="color" value={project.primaryColor} onChange={(event) => update("primaryColor", event.target.value)} /><input value={project.primaryColor} onChange={(event) => update("primaryColor", event.target.value)} /></span></label></div></div>

          <div className="editor-section"><h2>{text.business}</h2><div className="field-row"><label>{text.businessName}<input value={project.businessName} onChange={(event) => { const previousSlug = slugify(project.businessName); update("businessName", event.target.value); if (!project.slug || project.slug === previousSlug) update("slug", slugify(event.target.value)); }} /></label><label>{text.industry}<input value={project.industry} onChange={(event) => update("industry", event.target.value)} /></label></div><label>{text.eyebrow}<input value={project.eyebrow} onChange={(event) => update("eyebrow", event.target.value)} /></label><label>{text.headline}<textarea rows={2} value={project.tagline} onChange={(event) => update("tagline", event.target.value)} /></label><label>{text.description}<textarea rows={3} value={project.description} onChange={(event) => update("description", event.target.value)} /></label><div className="field-row"><label>{text.cta}<input value={project.primaryCta} onChange={(event) => update("primaryCta", event.target.value)} /></label><label>{text.hours}<input value={project.workingHours} onChange={(event) => update("workingHours", event.target.value)} /></label></div><label>{text.aboutTitle}<input value={project.aboutTitle} onChange={(event) => update("aboutTitle", event.target.value)} /></label></div>

          <div className="editor-section"><h2>{menuSite ? text.menu : text.services}</h2>{project.offers.map((offer, index) => <div className="offer-editor" key={index}><span>{String(index + 1).padStart(2, "0")}</span><div><input aria-label={`${index + 1}. title`} value={offer.name} onChange={(event) => updateOffer(index, "name", event.target.value)} /><input aria-label={`${index + 1}. description`} value={offer.description} onChange={(event) => updateOffer(index, "description", event.target.value)} /></div><input className="price-input" aria-label={`${index + 1}. price`} value={offer.price} onChange={(event) => updateOffer(index, "price", event.target.value)} /><button type="button" className="remove-editor-item" onClick={() => removeOffer(index)} aria-label={`${text.remove} ${index + 1}`}>×</button></div>)}<button type="button" className="add-editor-item" onClick={addOffer} disabled={project.offers.length >= 12}>{text.addItem}</button></div>

          <div className="editor-section"><h2>{text.benefits}</h2>{project.benefits.map((benefit, index) => <div className="simple-list-editor" key={index}><input value={benefit} onChange={(event) => updateList("benefits", index, event.target.value)} /><button type="button" onClick={() => removeBenefit(index)} aria-label={`${text.remove} ${index + 1}`}>×</button></div>)}<button type="button" className="add-editor-item" onClick={addBenefit} disabled={project.benefits.length >= 6}>{text.addBenefit}</button></div>

          <div className="editor-section"><h2>{text.media}</h2><label>{text.logo}<input type="url" placeholder="https://…" value={project.logoUrl} onChange={(event) => update("logoUrl", event.target.value)} /></label><label>{text.hero}<input type="url" placeholder="https://…" value={project.heroImageUrl} onChange={(event) => update("heroImageUrl", event.target.value)} /></label><label>{text.gallery}</label>{project.galleryUrls.map((url, index) => <input key={index} type="url" aria-label={`${text.gallery} ${index + 1}`} placeholder={`https://… (${index + 1})`} value={url} onChange={(event) => updateList("galleryUrls", index, event.target.value)} />)}</div>

          <div className="editor-section"><h2>{text.contact}</h2><div className="field-row"><label>{text.person}<input value={project.contactName} onChange={(event) => update("contactName", event.target.value)} /></label><label>{text.email}<input type="email" value={project.email} onChange={(event) => update("email", event.target.value)} /></label></div><div className="field-row"><label>{text.phone}<input value={project.phone} onChange={(event) => update("phone", event.target.value)} /></label><label>{text.whatsapp}<input value={project.whatsapp} onChange={(event) => update("whatsapp", event.target.value)} /></label></div><label>{text.address}<input value={project.address} onChange={(event) => update("address", event.target.value)} /></label><div className="field-row"><label>{text.instagram}<input value={project.instagram} onChange={(event) => update("instagram", event.target.value)} /></label><label>{text.map}<input type="url" placeholder="https://maps.google.com/…" value={project.mapUrl} onChange={(event) => update("mapUrl", event.target.value)} /></label></div><label>{text.slug}<span className="slug-field"><b>auradigital.ink/quicksite/</b><input value={project.slug} onChange={(event) => update("slug", slugify(event.target.value))} /></span></label><label>{text.note}<textarea rows={3} placeholder={text.notePlaceholder} value={project.requestMessage} onChange={(event) => update("requestMessage", event.target.value)} /></label></div>
          {error && <p className="form-error">{error}</p>}
          <button className="button submit-wide" onClick={submit} disabled={saving}>{saving ? text.submitting : text.submit}<span>→</span></button>
        </aside>
        <section className="preview-panel"><div className="preview-toolbar"><div><b>{selectedTemplate.name}</b><span>• {text.unsaved}</span></div><div className="device-toggle"><button className={view === "desktop" ? "active" : ""} onClick={() => setView("desktop")} aria-label="Desktop preview">▰</button><button className={view === "mobile" ? "active" : ""} onClick={() => setView("mobile")} aria-label="Mobile preview">▯</button></div></div><div className={`preview-stage ${view}`}><div className="browser-frame"><div className="browser-bar"><span><i /><i /><i /></span><b>auradigital.ink/quicksite/{project.slug || "site-address"}</b><em>Draft</em></div><SitePreview project={project} draft compact /></div></div></section>
      </div>
    </main>
  );
}
